// Copyright © 2026 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>, author Nicholas Turner <nicholas.turner@kdab.com>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

export component Foo {
    in-out property <int> foo;
    match foo {
        1: pass;
        else: Rectangle { }
    }
}

export component Bar {
    in-out property <int> foo;
    match foo {
        1: pass
        else: Rectangle { }
//      >  <error{Syntax error: expected ';'}
    }
}

export component Bar {
    in-out property <int> foo;
    match foo {
        1: pass;
        2: pass
        else: Rectangle { }
//      >  <error{Syntax error: expected ';'}
    }
}

export component Baz {
    in-out property <int> foo;
    match foo {
        1: Rectangle { }
        else: pass;
//            >  <error{Cannot use 'pass' in else case}
    }
}